version: 1.0.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
shallow_clone: true
cache:
- .\NameData
- .\ThirdPartyComponents
- .\LASI.App\Resources
nuget:
  account_feed: true
  project_feed: true
build:
  project: .\LASI.sln
  verbosity: minimal
before_test:
- ps: 
after_test:
- ps: dir -r ./LASI.App/*.dll
